package com.prelude.denoise.tiling;

import org.junit.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

/**
 * Golden vector: pins the Java Tiler's numeric semantics so the numpy
 * reference (quantization-deploy/tiler_ref.py) can be validated against them.
 *
 * The committed fixture (quantization-deploy/test/golden_tiler_vector.txt) is
 * NEVER overwritten by this test. Regeneration is explicit only:
 *   -Dtiler.golden.regenerate=true   (JUnit)  |  main("regenerate")  (CLI)
 *
 * Tile inferencer in the fixture: fixed 3x3 box blur, zero-padded outside the
 * tile, per channel — mirrored exactly in test_tiler_ref.py.
 */
public class TilerGoldenVectorTest {

    private static final int TILE = 8, HALO = 2, BLEND = 2;
    private static final float TOLERANCE = 1e-5f;

    /**
     * Fixed tile inferencer: TWO passes of 3x3 box blur, zero-padded outside the
     * tile (receptive-field radius 2 — so halo 1 vs 2 is observable; mirrored
     * exactly in test_tiler_ref.py).
     */
    static float[] boxBlurTile(float[] tile, int tileSize, int channels) {
        float[] tmp = new float[tile.length];
        float[] out = new float[tile.length];
        boxBlurPass(tile, tmp, tileSize, channels);
        boxBlurPass(tmp, out, tileSize, channels);
        return out;
    }

    private static void boxBlurPass(float[] in, float[] out, int tileSize, int channels) {
        for (int y = 0; y < tileSize; y++) {
            for (int x = 0; x < tileSize; x++) {
                for (int c = 0; c < channels; c++) {
                    float sum = 0f;
                    for (int dy = -1; dy <= 1; dy++) {
                        for (int dx = -1; dx <= 1; dx++) {
                            int ny = y + dy, nx = x + dx;
                            if (ny >= 0 && ny < tileSize && nx >= 0 && nx < tileSize) {
                                sum += in[(ny * tileSize + nx) * channels + c];
                            }
                        }
                    }
                    out[(y * tileSize + x) * channels + c] = sum / 9.0f;
                }
            }
        }
    }

    /** Deterministic input image: (x + 2*y + 0.5*c) / 32. */
    static float[] makeImage(int width, int height, int channels) {
        float[] img = new float[width * height * channels];
        for (int y = 0; y < height; y++) {
            for (int x = 0; x < width; x++) {
                for (int c = 0; c < channels; c++) {
                    img[(y * width + x) * channels + c] =
                        (x + 2 * y + 0.5f * c) / 32.0f;
                }
            }
        }
        return img;
    }

    private static final String[][] CASES = {
        // name, tileSize, halo, blend, width, height, channels
        {"multiTile", "8", "2", "2", "12", "10", "1"},
        {"smallImage", "8", "2", "2", "6", "5", "1"},
    };

    private Path fixturePath() {
        // unit-test working dir varies (module dir or repo root) — try both
        Path[] candidates = {
            Paths.get("test", "golden_tiler_vector.txt"),
            Paths.get("quantization-deploy", "test", "golden_tiler_vector.txt"),
        };
        for (Path p : candidates) {
            if (Files.exists(p)) {
                return p;
            }
        }
        return candidates[0];
    }

    private record GoldenCase(String name, Tiler tiler, int width, int height, int channels,
                              float[] input, float[] expected) {}

    /** Computes every case fresh from the real Tiler. */
    static List<GoldenCase> computeCases() {
        List<GoldenCase> cases = new ArrayList<>();
        for (String[] c : CASES) {
            int tileSize = Integer.parseInt(c[1]), halo = Integer.parseInt(c[2]);
            int blend = Integer.parseInt(c[3]), width = Integer.parseInt(c[4]);
            int height = Integer.parseInt(c[5]), channels = Integer.parseInt(c[6]);
            Tiler tiler = new Tiler(tileSize, halo, blend);
            float[] input = makeImage(width, height, channels);
            float[] out = tiler.process(input, width, height, channels,
                tile -> boxBlurTile(tile, tileSize, channels));
            cases.add(new GoldenCase(c[0], tiler, width, height, channels, input, out));
        }
        return cases;
    }

    static String renderFixture() {
        StringBuilder sb = new StringBuilder();
        sb.append("# tiler golden vector — generated by TilerGoldenVectorTest (Java float32)\n");
        sb.append("# regenerate explicitly only: -Dtiler.golden.regenerate=true\n");
        for (GoldenCase gc : computeCases()) {
            sb.append(String.format("case %s tileSize=%d haloSize=%d blendSize=%d width=%d height=%d channels=%d%n",
                gc.name(), gc.tiler().getTileSize(), gc.tiler().getHaloSize(),
                gc.tiler().getBlendSize(), gc.width(), gc.height(), gc.channels()));
            sb.append("input");
            for (float v : gc.input()) sb.append(' ').append(v);
            sb.append('\n');
            sb.append("expected");
            for (float v : gc.expected()) sb.append(' ').append(v);
            sb.append('\n');
        }
        return sb.toString();
    }

    static void regenerate(Path path) throws IOException {
        Files.createDirectories(path.toAbsolutePath().getParent());
        Files.writeString(path, renderFixture(), StandardCharsets.UTF_8);
        System.out.println("Golden fixture (re)generated: " + path.toAbsolutePath());
    }

    @Test
    public void tilerMatchesGoldenFixture() throws IOException {
        Path path = fixturePath();
        if (Boolean.getBoolean("tiler.golden.regenerate")) {
            regenerate(path);
            return;
        }
        assertTrue("Golden fixture missing: " + path.toAbsolutePath()
            + " (regenerate explicitly with -Dtiler.golden.regenerate=true)", Files.exists(path));

        List<String> lines = Files.readAllLines(path, StandardCharsets.UTF_8);
        List<GoldenCase> fresh = computeCases();
        int caseIdx = -1;
        for (String line : lines) {
            if (line.startsWith("case ")) {
                caseIdx++;
                assertTrue("fixture has more cases than computed", caseIdx < fresh.size());
                assertEquals("case name", fresh.get(caseIdx).name(), line.split("\\s+")[1]);
            } else if (line.startsWith("input ")) {
                float[] fixtureInput = parseFloats(line);
                float[] input = fresh.get(caseIdx).input();
                assertEquals("input length", input.length, fixtureInput.length);
                assertArrayClose("input", input, fixtureInput);
            } else if (line.startsWith("expected ")) {
                float[] fixtureExpected = parseFloats(line);
                float[] expected = fresh.get(caseIdx).expected();
                assertEquals("expected length", expected.length, fixtureExpected.length);
                assertArrayClose(fresh.get(caseIdx).name(), expected, fixtureExpected);
            }
        }
        assertEquals("fixture case count", fresh.size(), caseIdx + 1);
    }

    private static float[] parseFloats(String line) {
        String[] parts = line.trim().split("\\s+");
        float[] out = new float[parts.length - 1];
        for (int i = 1; i < parts.length; i++) {
            out[i - 1] = Float.parseFloat(parts[i]);
        }
        return out;
    }

    private static void assertArrayClose(String what, float[] a, float[] b) {
        double maxDiff = 0;
        for (int i = 0; i < a.length; i++) {
            maxDiff = Math.max(maxDiff, Math.abs(a[i] - b[i]));
        }
        assertTrue(String.format("%s: max abs diff %g exceeds %g", what, maxDiff, TOLERANCE),
            maxDiff <= TOLERANCE);
    }

    /** Fixture bootstrap without Gradle: java ... TilerGoldenVectorTest regenerate */
    public static void main(String[] args) throws IOException {
        if (args.length == 1 && "regenerate".equals(args[0])) {
            regenerate(Paths.get("test", "golden_tiler_vector.txt").toAbsolutePath());
        } else {
            System.err.println("usage: TilerGoldenVectorTest regenerate");
            System.exit(2);
        }
    }
}
